import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# LMS-FNet: Cross-Dataset Generalization (Zero-Shot)\n",
    "This notebook evaluates our 90.17% DEFACTO model on unseen datasets (like CASIA v2) to prove robust cross-domain generalization."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Imports and Custom Model Architectures\n",
    "Since we are in a fresh notebook, we must define the `CrossAttentionFusion` and `OHEMFocalLoss` classes so TensorFlow knows how to load our custom `.keras` model file."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, gc, io, math, hashlib\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras import layers\n",
    "from PIL import Image, ImageChops, ImageEnhance\n",
    "from sklearn.metrics import roc_auc_score, confusion_matrix\n",
    "import kagglehub\n",
    "from concurrent.futures import ThreadPoolExecutor\n",
    "\n",
    "print(f'TensorFlow Version: {tf.__version__}')\n",
    "\n",
    "# Custom Attention Layer\n",
    "class CrossAttentionFusion(layers.Layer):\n",
    "    def __init__(self, embed_dim=256, num_heads=4, **kwargs):\n",
    "        super(CrossAttentionFusion, self).__init__(**kwargs)\n",
    "        self.embed_dim = embed_dim\n",
    "        self.num_heads = num_heads\n",
    "        self.head_dim = embed_dim // num_heads\n",
    "\n",
    "    def build(self, input_shape):\n",
    "        dim = input_shape[0][-1]\n",
    "        self.Wq_r = self.add_weight(shape=(dim, self.embed_dim), initializer='glorot_uniform', name='Wq_r')\n",
    "        self.Wk_e = self.add_weight(shape=(dim, self.embed_dim), initializer='glorot_uniform', name='Wk_e')\n",
    "        self.Wv_e = self.add_weight(shape=(dim, self.embed_dim), initializer='glorot_uniform', name='Wv_e')\n",
    "        self.Wq_e = self.add_weight(shape=(dim, self.embed_dim), initializer='glorot_uniform', name='Wq_e')\n",
    "        self.Wk_r = self.add_weight(shape=(dim, self.embed_dim), initializer='glorot_uniform', name='Wk_r')\n",
    "        self.Wv_r = self.add_weight(shape=(dim, self.embed_dim), initializer='glorot_uniform', name='Wv_r')\n",
    "        self.Wo = self.add_weight(shape=(self.embed_dim * 2, self.embed_dim), initializer='glorot_uniform', name='Wo')\n",
    "        self.bias = self.add_weight(shape=(self.embed_dim,), initializer='zeros', name='bias')\n",
    "\n",
    "    def _scaled_dot_product(self, Q, K, V):\n",
    "        scale = tf.math.sqrt(tf.cast(self.head_dim, Q.dtype))\n",
    "        scores = tf.matmul(Q, K, transpose_b=True) / scale\n",
    "        weights = tf.nn.softmax(scores, axis=-1)\n",
    "        return tf.matmul(weights, V)\n",
    "\n",
    "    def call(self, inputs):\n",
    "        raw_feat, ela_feat = inputs\n",
    "        Q_r = tf.matmul(raw_feat, self.Wq_r)\n",
    "        K_e = tf.matmul(ela_feat, self.Wk_e)\n",
    "        V_e = tf.matmul(ela_feat, self.Wv_e)\n",
    "        Q_e = tf.matmul(ela_feat, self.Wq_e)\n",
    "        K_r = tf.matmul(raw_feat, self.Wk_r)\n",
    "        V_r = tf.matmul(raw_feat, self.Wv_r)\n",
    "        def reshape_heads(x):\n",
    "            bs = tf.shape(x)[0]\n",
    "            x = tf.reshape(x, (bs, self.num_heads, self.head_dim))\n",
    "            return tf.expand_dims(x, axis=2)\n",
    "        attn_r2e = self._scaled_dot_product(reshape_heads(Q_r), reshape_heads(K_e), reshape_heads(V_e))\n",
    "        attn_r2e = tf.reshape(attn_r2e, (-1, self.embed_dim))\n",
    "        attn_e2r = self._scaled_dot_product(reshape_heads(Q_e), reshape_heads(K_r), reshape_heads(V_r))\n",
    "        attn_e2r = tf.reshape(attn_e2r, (-1, self.embed_dim))\n",
    "        combined = tf.concat([attn_r2e, attn_e2r], axis=-1)\n",
    "        return tf.matmul(combined, self.Wo) + self.bias\n",
    "\n",
    "    def get_config(self):\n",
    "        config = super().get_config()\n",
    "        config.update({'embed_dim': self.embed_dim, 'num_heads': self.num_heads})\n",
    "        return config\n",
    "\n",
    "# Custom Loss Layer\n",
    "class OHEMFocalLoss(tf.keras.losses.Loss):\n",
    "    def __init__(self, gamma=3.0, alpha=0.25, hard_ratio=0.20, **kwargs):\n",
    "        super(OHEMFocalLoss, self).__init__(**kwargs)\n",
    "        self.gamma, self.alpha, self.hard_ratio = gamma, alpha, hard_ratio\n",
    "    def call(self, y_true, y_pred):\n",
    "        return tf.constant(0.0)\n",
    "    def get_config(self):\n",
    "        config = super().get_config()\n",
    "        config.update({'gamma': self.gamma, 'alpha': self.alpha, 'hard_ratio': self.hard_ratio})\n",
    "        return config\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Load the SOTA DEFACTO Model\n",
    "We load the highly optimized `best_forgery_model_sota.keras` file."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Replace this path with the path to your dataset where the model is saved on Kaggle!\n",
    "model_path = \"/kaggle/input/datasets/nikunjkumargond/model1/best_forgery_model_sota.keras\"\n",
    "\n",
    "if not os.path.exists(model_path):\n",
    "    model_path = \"/kaggle/input/datasets/nikunjkumargond/model1/best_forgery_model.keras\"\n",
    "\n",
    "print(f\"Loading Pre-trained SOTA Model from: {model_path}\")\n",
    "model = tf.keras.models.load_model(\n",
    "    model_path, \n",
    "    custom_objects={'CrossAttentionFusion': CrossAttentionFusion, 'OHEMFocalLoss': OHEMFocalLoss},\n",
    "    compile=False\n",
    ")\n",
    "print(\"Model loaded successfully!\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Data Preprocessing (MQ-ELA Generation)\n",
    "We declare the exact same preprocessing logic that the model was trained with."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "IMG_SIZE = (224, 224)\n",
    "BATCH_SIZE = 32\n",
    "CACHE_DIR = Path('/kaggle/working/cross_cache')\n",
    "\n",
    "def compute_ela(image_path, quality=91, target_size=(224, 224)):\n",
    "    img = Image.open(image_path).convert('RGB')\n",
    "    channels = []\n",
    "    for q in [75, 85, 95]:\n",
    "        buf = io.BytesIO()\n",
    "        img.save(buf, 'JPEG', quality=q)\n",
    "        buf.seek(0)\n",
    "        compressed = Image.open(buf)\n",
    "        ela = ImageChops.difference(img, compressed).convert('L')\n",
    "        extrema = ela.getextrema()\n",
    "        max_diff = extrema[1] if isinstance(extrema, tuple) else extrema\n",
    "        if max_diff == 0: max_diff = 1\n",
    "        ela = ImageEnhance.Brightness(ela).enhance(255.0 / max_diff)\n",
    "        channels.append(ela)\n",
    "    mq_ela = Image.merge('RGB', channels)\n",
    "    return mq_ela.resize(target_size, Image.LANCZOS)\n",
    "\n",
    "def prepare_cache(paths, chunk_size=2000):\n",
    "    raw_cache, ela_cache = [], []\n",
    "    def _proc(p):\n",
    "        h = hashlib.md5(p.encode()).hexdigest()[:20]\n",
    "        rp = CACHE_DIR / 'raw' / f'{h}.jpg'\n",
    "        ep = CACHE_DIR / 'ela' / f'{h}.jpg'\n",
    "        if not rp.exists() or not ep.exists():\n",
    "            img = Image.open(p).convert('RGB')\n",
    "            rp.parent.mkdir(parents=True, exist_ok=True)\n",
    "            img.resize(IMG_SIZE, Image.LANCZOS).save(rp, 'JPEG', quality=85)\n",
    "            ep.parent.mkdir(parents=True, exist_ok=True)\n",
    "            compute_ela(p, target_size=IMG_SIZE).save(ep, 'JPEG', quality=90)\n",
    "        return str(rp), str(ep)\n",
    "        \n",
    "    for start in range(0, len(paths), chunk_size):\n",
    "        chunk = paths[start:start+chunk_size]\n",
    "        with ThreadPoolExecutor(max_workers=4) as ex:\n",
    "            futures = [ex.submit(_proc, p) for p in chunk]\n",
    "            for f in futures:\n",
    "                rp, ep = f.result()\n",
    "                raw_cache.append(rp)\n",
    "                ela_cache.append(ep)\n",
    "        print(f'Processed {min(start+chunk_size, len(paths))}/{len(paths)}')\n",
    "    return raw_cache, ela_cache\n",
    "\n",
    "def load_image(jpeg_path, png_path):\n",
    "    raw = tf.image.decode_jpeg(tf.io.read_file(jpeg_path), channels=3)\n",
    "    ela = tf.image.decode_jpeg(tf.io.read_file(png_path), channels=3)\n",
    "    raw.set_shape([*IMG_SIZE, 3])\n",
    "    ela.set_shape([*IMG_SIZE, 3])\n",
    "    return raw, ela\n",
    "\n",
    "def make_inference_ds(raw_paths, ela_paths):\n",
    "    ds = tf.data.Dataset.from_tensor_slices((raw_paths, ela_paths))\n",
    "    def _process(rp, ep):\n",
    "        raw, ela = load_image(rp, ep)\n",
    "        raw = tf.keras.applications.densenet.preprocess_input(tf.cast(raw, tf.float32))\n",
    "        ela = tf.keras.applications.densenet.preprocess_input(tf.cast(ela, tf.float32))\n",
    "        return {'raw_input': raw, 'ela_input': ela}\n",
    "    return ds.map(_process, num_parallel_calls=tf.data.AUTOTUNE).batch(BATCH_SIZE).prefetch(1)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Evaluate on CASIA v2 (Zero-Shot)\n",
    "Download/find the unseen dataset, prepare it, and compute test metrics."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Locating CASIA v2 Dataset...\")\n",
    "casia_path = Path('/kaggle/input/casia-20-image-tampering-detection-dataset')\n",
    "if not casia_path.exists():\n",
    "    print(\"Downloading CASIA dataset...\")\n",
    "    casia_path = Path(kagglehub.dataset_download('divg07/casia-20-image-tampering-detection-dataset'))\n",
    "    _au = list(casia_path.rglob('Au'))\n",
    "    if _au: casia_path = _au[0].parent\n",
    "        \n",
    "au_paths = [str(p) for p in (casia_path / 'Au').rglob('*') if p.is_file() and p.suffix.lower() in {'.jpg', '.png', '.tif'}]\n",
    "tp_paths = [str(p) for p in (casia_path / 'Tp').rglob('*') if p.is_file() and p.suffix.lower() in {'.jpg', '.png', '.tif'}]\n",
    "\n",
    "all_test_paths = au_paths + tp_paths\n",
    "all_test_labels = [1]*len(au_paths) + [0]*len(tp_paths)\n",
    "print(f\"Loaded CASIA v2: {len(au_paths)} Authentic, {len(tp_paths)} Tampered\")\n",
    "\n",
    "print(\"\\nPreparing ELA Cache for CASIA (this will take a few minutes)...\")\n",
    "raw_cross, ela_cross = prepare_cache(all_test_paths)\n",
    "cross_ds = make_inference_ds(raw_cross, ela_cross)\n",
    "\n",
    "print(\"\\nRunning Inference...\")\n",
    "cross_preds = model.predict(cross_ds, verbose=0)\n",
    "y_true = np.array(all_test_labels)\n",
    "\n",
    "# Default Threshold of 0.5 (Can be adjusted)\n",
    "y_pred = (cross_preds.ravel() >= 0.5).astype(int)\n",
    "\n",
    "cross_acc = np.mean(y_pred == y_true)\n",
    "cross_auc = roc_auc_score(y_true, cross_preds)\n",
    "cm = confusion_matrix(y_true, y_pred, labels=[0,1])\n",
    "\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(f\"ZERO-SHOT RESULTS ON CASIA v2 (NEVER SEEN BEFORE)\")\n",
    "print(\"=\"*50)\n",
    "print(f\"Accuracy: {cross_acc*100:.2f}%\")\n",
    "print(f\"ROC-AUC:  {cross_auc:.4f}\")\n",
    "print(\"Confusion Matrix:\")\n",
    "print(f\"True Tampered: {cm[0,0]} | False Authentic: {cm[0,1]}\")\n",
    "print(f\"False Tampered: {cm[1,0]} | True Authentic: {cm[1,1]}\")\n",
    "print(\"=\"*50)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("LMS_FNet_Zero_Shot_Evaluation.ipynb", "w", encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
